### ISSUE TITLE
Doesn't function properly when canvas scaler is attached to the canves

### ISSUE THREAD

**Issue by maikuthe1** [FarrokhGames/Inventory#10]
When there is a canvas scaler attached to the canvas the dragged items don't update their position correctly.

**Comment by Shackless** [comment]
Same here when setting `UI Scale Mode` to `Scale with Screen Size`. Did you find a solution for this?

**Comment by DoktorAce** [comment]
Sorry it took so long, but this has now been fixed on the develop branch with [the latest commit](https://github.com/FarrokhGames/Inventory/commit/2983b6492d76126a36788a17279ad338fc1a4ca2), along with making the project compatible with Unity 2019.3.
Please note that I've made some slight changes to the API in preparations for turning this whole thing into a package.
