### ISSUE TITLE
Setting the canvas to overlay mode should be on the docs!

### ISSUE THREAD

**Issue by gabahulk** [FarrokhGames/Inventory#7]
Hello!
I've been toying around with the inventory and it's very cool! I'm very thankful for it!
I've had some weird behavior with the controller because my canvas was not in overlay mode, and I think it'd be nice to be in the docs!

**Comment by DoktorAce** [comment]
Hi!
Thank you for your thoughts. Im curios what this weird behavor was?
Hopefully its something that can be fixed.

**Comment by DoktorAce** [comment]
Hi,

I just managed to track down and fixed this issue, and the inventory is now tested using all three canvas render modes (Screen Space Overlay, Screen Space Camera and World Space)
